### ISSUE TITLE
Deprecated methods.

### ISSUE THREAD

**Issue by toddfreese** [spothero/SHEmailValidator#4]
Is there update to stop using deprecated methods?

SHAutocorrectSuggestionView.m:83:35: 'sizeWithFont:constrainedToSize:lineBreakMode:' is deprecated: first deprecated in iOS 7.0 - Use -boundingRectWithSize:options:attributes:context:

SHAutocorrectSuggestionView.m:84:45: 'sizeWithFont:constrainedToSize:lineBreakMode:' is deprecated: first deprecated in iOS 7.0 - Use -boundingRectWithSize:options:attributes:context:

SHAutocorrectSuggestionView.m:164:17: 'drawInRect:withFont:lineBreakMode:alignment:' is deprecated: first deprecated in iOS 7.0 - Use -drawInRect:withAttributes:

SHAutocorrectSuggestionView.m:167:25: 'drawInRect:withFont:lineBreakMode:alignment:' is deprecated: first deprecated in iOS 7.0 - Use -drawInRect:withAttributes:

**Comment by akki7017** [comment]
1. CGSize titleSize; // = [title sizeWithFont:self.titleFont constrainedToSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) lineBreakMode:NSLineBreakByWordWrapping];
        
        {
            NSMutableParagraphStyle *style = [[NSMutableParagraphStyle alloc] init];
            [style setLineBreakMode:NSLineBreakByWordWrapping];
            
             titleSize = CGRectIntegral([title boundingRectWithSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) options:NSStringDrawingUsesLineFragmentOrigin attributes:@{ NSParagraphStyleAttributeName: style, NSFontAttributeName: self.titleFont } context:nil]).size;
        }


2. CGSize suggestionSize; // = [suggestion sizeWithFont:self.suggestionFont constrainedToSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) lineBreakMode:NSLineBreakByCharWrapping];
       
        
        {
            NSMutableParagraphStyle *style = [[NSMutableParagraphStyle alloc] init];
            [style setLineBreakMode:NSLineBreakByCharWrapping];
            
            suggestionSize = CGRectIntegral([suggestion boundingRectWithSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) options:NSStringDrawingUsesLineFragmentOrigin attributes:@{ NSParagraphStyleAttributeName: style, NSFontAttributeName: self.suggestionFont } context:nil]).size;
        }



3. CGSize titleSize; // = [title sizeWithFont:self.titleFont constrainedToSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) lineBreakMode:NSLineBreakByWordWrapping];
        
        {
            NSMutableParagraphStyle *style = [[NSMutableParagraphStyle alloc] init];
            [style setLineBreakMode:NSLineBreakByWordWrapping];
            
             titleSize = CGRectIntegral([title boundingRectWithSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) options:NSStringDrawingUsesLineFragmentOrigin attributes:@{ NSParagraphStyleAttributeName: style, NSFontAttributeName: self.titleFont } context:nil]).size;
        }
        

4. CGSize suggestionSize; // = [suggestion sizeWithFont:self.suggestionFont constrainedToSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) lineBreakMode:NSLineBreakByCharWrapping];
       
        
        {
            NSMutableParagraphStyle *style = [[NSMutableParagraphStyle alloc] init];
            [style setLineBreakMode:NSLineBreakByCharWrapping];
            
            suggestionSize = CGRectIntegral([suggestion boundingRectWithSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) options:NSStringDrawingUsesLineFragmentOrigin attributes:@{ NSParagraphStyleAttributeName: style, NSFontAttributeName: self.suggestionFont } context:nil]).size;
        }

**Comment by akki7017** [comment]
1. 

CGSize titleSize; // = [title sizeWithFont:self.titleFont constrainedToSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) lineBreakMode:NSLineBreakByWordWrapping];
        {
            NSMutableParagraphStyle *style = [[NSMutableParagraphStyle alloc] init];
            [style setLineBreakMode:NSLineBreakByWordWrapping];
            
             titleSize = CGRectIntegral([title boundingRectWithSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) options:NSStringDrawingUsesLineFragmentOrigin attributes:@{ NSParagraphStyleAttributeName: style, NSFontAttributeName: self.titleFont } context:nil]).size;
        }


2. 

CGSize suggestionSize; // = [suggestion sizeWithFont:self.suggestionFont constrainedToSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) lineBreakMode:NSLineBreakByCharWrapping];
       
        
        {
            NSMutableParagraphStyle *style = [[NSMutableParagraphStyle alloc] init];
            [style setLineBreakMode:NSLineBreakByCharWrapping];
            
            suggestionSize = CGRectIntegral([suggestion boundingRectWithSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) options:NSStringDrawingUsesLineFragmentOrigin attributes:@{ NSParagraphStyleAttributeName: style, NSFontAttributeName: self.suggestionFont } context:nil]).size;
        }



3. 

CGSize titleSize; // = [title sizeWithFont:self.titleFont constrainedToSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) lineBreakMode:NSLineBreakByWordWrapping];
        
        {
            NSMutableParagraphStyle *style = [[NSMutableParagraphStyle alloc] init];
            [style setLineBreakMode:NSLineBreakByWordWrapping];
            
             titleSize = CGRectIntegral([title boundingRectWithSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) options:NSStringDrawingUsesLineFragmentOrigin attributes:@{ NSParagraphStyleAttributeName: style, NSFontAttributeName: self.titleFont } context:nil]).size;
        }
        

4. 

CGSize suggestionSize; // = [suggestion sizeWithFont:self.suggestionFont constrainedToSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) lineBreakMode:NSLineBreakByCharWrapping];
       
        
        {
            NSMutableParagraphStyle *style = [[NSMutableParagraphStyle alloc] init];
            [style setLineBreakMode:NSLineBreakByCharWrapping];
            
            suggestionSize = CGRectIntegral([suggestion boundingRectWithSize:CGSizeMake(kMaxWidth - kDismissButtonWidth, MAXFLOAT) options:NSStringDrawingUsesLineFragmentOrigin attributes:@{ NSParagraphStyleAttributeName: style, NSFontAttributeName: self.suggestionFont } context:nil]).size;
        }

**Comment by oguzman** [comment]
PR created to avoid and keep code clean of these deprecated warnings.
https://github.com/spothero/SHEmailValidator/pull/10

**Comment by designatednerd** [comment]
Closing as this was merged some time ago.
