### ISSUE TITLE
Analyze warning.

### ISSUE THREAD

**Issue by toddfreese** [spothero/SHEmailValidator#5]
If you run the Xcode analyzer you get the following warning.

SHEmailValidator/NSString+LevenshteinDistance.m:37:7: Result of 'malloc' is converted to a pointer of type 'NSInteger', which is incompatible with sizeof operand type 'NSUInteger'

**Comment by designatednerd** [comment]
Looks like this warning got fixed a while back but this issue was never closed. Thank you for the heads up!
