### ISSUE TITLE
New Pod release?

### ISSUE THREAD

**Issue by SlaunchaMan** [spothero/SHEmailValidator#9]
We’d like to use a version of SHEmailValidator with #8 merged in. Would you be able to release an update with it included?

**Comment by ebrenesc** [comment]
Sure i merged it already a few days ago forgot about cocoapods, i ll try to get it up in cocoapods  later today

**Comment by SlaunchaMan** [comment]
Thanks!

**Comment by ebrenesc** [comment]
Version 1.0.3 is up on github, closing

**Comment by SlaunchaMan** [comment]
:+1:
